book_repo: greengage-db/docs/book

public_host: localhost:9292

sections:
- repository:
    name: content
  directory: pxf/WIP
  subnav_template: pxf-subnav

template_variables:
  book_title: Greengage Database PXF Documentation
  book_title_short:  Greengage Database PXF Docs
  domain_name: greengagedb.org
  product_link: <div class="header-item"><a href="https://greengagedb.org/en/docs-gg/current/intro.html">To Greengage Database Docs</a></div>
  product_url: https://greengagedb.org
  support_url: https://greengagedb.org

broken_link_exclusions: iefix|arrowhead
