version: "3"
services:
  mdw:
    image: "ggdb6_pxf_automation:it"
    restart: unless-stopped
    working_dir: /home/gpadmin
    hostname: mdw
    ports:
      - "5435:5432"
      - "5005:5005"
    environment:
      - HOSTNAME=mdw
      - DOCKER_GG_CLUSTER_HOSTS=mdw,sdw1,sdw2
      - DOCKER_GG_MASTER_SERVER=mdw
      - DOCKER_GG_SEGMENT_SERVERS=sdw1,sdw2
      - DOCKER_GG_PRIMARY_SEGMENTS_PER_HOST=3
      - DOCKER_GG_WITH_MIRROR=false
      - HIVE_SERVER_HOST=hadoop
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    volumes:
      - "m2:/home/gpadmin/.m2:rw"
      - "share-lib:/usr/local/greengage-db-devel/pxf/share/:rw"
      - "./conf/cluster.xml:/home/gpadmin/workspace/pxf/automation/src/test/resources/sut/default.xml:ro"
      - "./conf/servers/hbase-site.xml:/etc/hbase/conf/hbase-site.xml:ro"
      - "./conf/encryption/pxfkeystore.jks:/usr/local/greengage-db-devel/pxf/conf/pxfkeystore.jks:ro"
      - "./conf/encryption/jdbc-site.xml:/usr/local/greengage-db-devel/pxf/templates/encryption/jdbc-site.xml:ro"
      - "./conf/oracle/jdbc-site.xml:/usr/local/greengage-db-devel/pxf/templates/oracle/jdbc-site.xml:ro"
      - "./conf/named-query/jdbc-site.xml:/usr/local/greengage-db-devel/pxf/templates/named-query/jdbc-site.xml:ro"
      - "./conf/named-query/named_query.sql:/usr/local/greengage-db-devel/pxf/templates/named-query/named_query.sql:ro"
      - "./conf/mysql/jdbc-site.xml:/usr/local/greengage-db-devel/pxf/templates/mysql/jdbc-site.xml:ro"
      - "./conf/backpressure/jdbc-site.xml:/usr/local/greengage-db-devel/pxf/templates/backpressure/jdbc-site.xml:ro"
      - "./conf/pxf-reload/jdbc-site.xml:/usr/local/greengage-db-devel/pxf/templates/pxf-reload/jdbc-site.xml:ro"
      - "test-data:/home/gpadmin/pxf_src/automation/src/test/resources/data"
    healthcheck:
      test:  sudo -H -u gpadmin bash -l -c "psql -d postgres -U gpadmin -Atc 'SELECT 1;'"
      interval: 30s
      timeout: 15s
      retries: 3
    depends_on:
      - sdw1
    privileged: true
    sysctls:
      kernel.sem: 500 1024000 200 4096
      net.unix.max_dgram_qlen: 4096

  sdw1:
    image: "ggdb6_pxf_automation:it"
    restart: unless-stopped
    privileged: true
    hostname: sdw1
    ports:
      - "8001:8000"
    environment:
      - HOSTNAME=sdw1
      - DOCKER_GG_CLUSTER_HOSTS=mdw,sdw1,sdw2
      - DOCKER_GG_MASTER_SERVER=mdw
      - DOCKER_GG_SEGMENT_SERVERS=sdw1,sdw2
      - DOCKER_GG_PRIMARY_SEGMENTS_PER_HOST=3
      - DOCKER_GG_WITH_MIRROR=false
      - HIVE_SERVER_HOST=hadoop
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    volumes:
      - "./conf/servers:/usr/local/greengage-db-devel/pxf/servers/default/:ro"
      - "./conf/pxf-profile.xml:/usr/local/greengage-db-devel/pxf/conf/pxf-profiles.xml:ro"
      - "./conf/encryption/pxfkeystore.jks:/usr/local/greengage-db-devel/pxf/conf/pxfkeystore.jks:ro"
    healthcheck:
      test:  netstat -an | grep 5888 > /dev/null; if [ 0 != $$? ]; then exit 1; fi;
      interval: 30s
      timeout: 15s
      retries: 3
    sysctls:
      kernel.sem: 500 1024000 200 4096
      net.unix.max_dgram_qlen: 4096

  sdw2:
    image: "ggdb6_pxf_automation:it"
    restart: unless-stopped
    privileged: true
    hostname: sdw2
    ports:
      - "8002:8000"
    environment:
      - HOSTNAME=sdw2
      - DOCKER_GG_CLUSTER_HOSTS=mdw,sdw1,sdw2
      - DOCKER_GG_MASTER_SERVER=mdw
      - DOCKER_GG_SEGMENT_SERVERS=sdw1,sdw2
      - DOCKER_GG_PRIMARY_SEGMENTS_PER_HOST=3
      - DOCKER_GG_WITH_MIRROR=false
      - HIVE_SERVER_HOST=hadoop
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    volumes:
      - "./conf/servers:/usr/local/greengage-db-devel/pxf/servers/default/:ro"
      - "./conf/pxf-profile.xml:/usr/local/greengage-db-devel/pxf/conf/pxf-profiles.xml:ro"
      - "./conf/encryption/pxfkeystore.jks:/usr/local/greengage-db-devel/pxf/conf/pxfkeystore.jks:ro"
    healthcheck:
      test: netstat -an | grep 5888 > /dev/null; if [ 0 != $$? ]; then exit 1; fi;
      interval: 30s
      timeout: 15s
      retries: 3
    sysctls:
      kernel.sem: 500 1024000 200 4096
      net.unix.max_dgram_qlen: 4096

  hadoop:
    image: pxf-hadoop:3.3.6
    restart: unless-stopped
    container_name: hadoop
    environment:
      - CLUSTER_NAME=pxf-hadoop
    env_file:
      - ./hadoop/hadoop.env
    ports:
      - "50070:50070"
      - "10000:10000"
      - "10002:10002"
      - "16010:16010" # HBase UI
      - "8088:8088"
      - "8042:8042"
      - "9864:9864"
    volumes:
      - "share-lib:/share:rw"
      - "./hadoop/hive-env.sh:/opt/hive/conf/hive-env.sh:ro"
      - "./hadoop/hbase-site.xml:/opt/hbase/conf/hbase-site.xml:ro"
      - "test-data:/tmp/test_data"
    healthcheck:
      test: bash /healthcheck_hadoop.sh
      interval: 30s
      timeout: 15s
      retries: 5
    depends_on:
      - hive-metastore-db

  hive-metastore-db:
    image: "docker.io/library/postgres:12.0"
    restart: unless-stopped
    container_name: hive-metastore-db
    hostname: hive-metastore-db
    environment:
      POSTGRES_DB: 'metastore'
      POSTGRES_USER: 'hive'
      POSTGRES_PASSWORD: 'hive'
    ports:
      - '5432:5432'
    healthcheck:
      test: psql -d metastore -U hive -Atc 'SELECT 1;'
      interval: 30s
      timeout: 15s
      retries: 3

  oracle:
    image: "haoyu233/oracle-12c-ee"
    restart: unless-stopped
    container_name: oracle
    hostname: oracle
    privileged: true
    ports:
      - '1521:1521'
      - '8080:8080'
    healthcheck:
      test: echo "SELECT 333 from dual;" | sqlplus -L system/oracle@ORCL | grep 333 > /dev/null; if [ 0 != $$? ]; then exit 1; fi;
      interval: 30s
      timeout: 15s
      retries: 3

  mysql:
    image: "mysql:8.3.0"
    restart: unless-stopped
    container_name: mysql
    hostname: mysql
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpwd
      MYSQL_DATABASE: gpexternal
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpwd
    ports:
      - '3306:3306'
    healthcheck:
      test: mysql -u mysqluser -pmysqlpwd --disable-column-names -e 'select 111' | grep 111 > /dev/null; if [ 0 != $$? ]; then exit 1; fi
      interval: 30s
      timeout: 15s
      retries: 3

  minio:
    image: hub.adsw.io/adbm/minio:RELEASE.2024-07-15T19-02-30Z
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - "MINIO_ACCESS_KEY=minio"
      - "MINIO_SECRET_KEY=minio123"
      - "MINIO_SERVER_URL=http://minio.local:9000"
      - "MINIO_OPTS=--console-address :9001"
      - "MINIO_API_SELECT_PARQUET=on"
    command: server /export
    hostname: minio.local
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      default:
        aliases:
          - minio.local

networks:
  default:
    name: pxf-automation

volumes:
  m2:
  share-lib:
  test-data: