# Release creation workflow
name: Greengage release

on:
  release:
    types: [published, edited]

concurrency:
  group: Greengage CI-${{ github.ref }}
  cancel-in-progress: false

jobs:
  upload-to-release:
    strategy:
      fail-fast: false
      matrix:
        include:
        - version: -6-devel
          extensions: deb ddeb
          artifact_name: pxf-packages-6-devel
        # - '7-devel'
        # - '6-stable'
        # - '7-stable'

    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read 
    steps:

      - name: Restore Debian artifacts from cache
        uses: actions/cache/restore@v4
        id: cache-restore
        with:
          path: ${{ matrix.artifact_name }}
          key:  ${{ matrix.artifact_name }}-${{ github.sha }}

      - name: Upload packages to release
        uses: greengagedb/greengage-ci/.github/actions/upload-pkgs-to-release@main
        with:
          version: ${{ matrix.version }}
          artifact_name: ${{ matrix.artifact_name }}
          package_name: pxf
          extensions: deb ddeb
