# greengage-reusable-tests-integration.yml
name: Greengage PXF Reusable Integration Tests

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      version:
        required: true
        type: string
      tag:
        required: true
        type: string
      tests:
        required: true
        type: string  # JSON string with test matrix

jobs:
  integration:
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(inputs.tests) }}

    name: Test ${{ matrix.test }}${{ matrix.fdw && ' FDW' || '' }}${{ matrix.ssl && ' SSL' || '' }} on ${{ inputs.image }}${{ inputs.version }}_ubuntu:${{ inputs.tag }}

    runs-on: ubuntu-latest
    env:
      DEV_HOME: /home/gpadmin
      PXF_HOME: /usr/local/greengage-db-devel/pxf
      GPHOME:   /usr/local/greengage-db-devel
      PROFILE: ${{ matrix.test }}
      GROUP: ${{ matrix.test }}
      USE_FDW: ${{ matrix.fdw }}
      USE_SSL: ${{ matrix.ssl }}
      GGDB_IMAGE: ${{ inputs.image }}${{ inputs.version }}_ubuntu:${{ inputs.tag }}
      IT_IMAGE: ${{ inputs.image }}${{ inputs.version }}_ubuntu_pxf_automation
      IT_TAG: ${{ inputs.tag }}
      JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
      DEBIAN_FRONTEND: noninteractive

    steps:
      # Maximize build space for Docker
      - name: Maximize disk space
        uses: greengagedb/greengage-ci/.github/actions/maximize-disk-space@v19

      - uses: actions/checkout@v4

      - name: Build ${{ env.IT_IMAGE }}:${{ env.IT_TAG }} image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ci/Dockerfile.integration
          tags: ${{ env.IT_IMAGE }}:${{ env.IT_TAG }}
          build-args: GGDB_IMAGE=${{ env.GGDB_IMAGE }}

      - name: Run ${{ matrix.test }} integration test
        run: |
          set -ex
          cd automation/env
          bash it.sh

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-ggdb${{ inputs.version }}-${{ inputs.tag }}-${{ matrix.test }}${{ matrix.fdw && '-fdw' || '' }}${{ matrix.ssl && '-ssl' || '' }}
          path: automation/env/artifacts/
          retention-days: 7
